## Switches
set_property PACKAGE_PIN V17 [get_ports {in2[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {in2[0]}]
set_property PACKAGE_PIN V16 [get_ports {in2[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {in2[1]}]
set_property PACKAGE_PIN W16 [get_ports {in2[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {in2[2]}]
set_property PACKAGE_PIN W17 [get_ports {in2[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {in2[3]}]
set_property PACKAGE_PIN W15 [get_ports {in1[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {in1[0]}]
set_property PACKAGE_PIN V15 [get_ports {in1[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {in1[1]}]
set_property PACKAGE_PIN W14 [get_ports {in1[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {in1[2]}]
set_property PACKAGE_PIN W13 [get_ports {in1[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {in1[3]}]

set_property PACKAGE_PIN R2 [get_ports {control[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {control[3]}]
set_property PACKAGE_PIN T1 [get_ports {control[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {control[2]}]
set_property PACKAGE_PIN U1 [get_ports {control[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {control[1]}]
set_property PACKAGE_PIN W2 [get_ports {control[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {control[0]}]
## LEDs
set_property PACKAGE_PIN U16 [get_ports {out1[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {out1[0]}]
set_property PACKAGE_PIN E19 [get_ports {out1[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {out1[1]}]
set_property PACKAGE_PIN U19 [get_ports {out1[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {out1[2]}]
set_property PACKAGE_PIN V19 [get_ports {out1[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {out1[3]}]
set_property PACKAGE_PIN W18 [get_ports {out1[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {out1[4]}]
set_property PACKAGE_PIN U15 [get_ports {out1[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {out1[5]}]
set_property PACKAGE_PIN U14 [get_ports {out1[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {out1[6]}]
set_property PACKAGE_PIN V14 [get_ports {out1[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {out1[7]}]

## Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]